// Action Types
export default {
  CREATE_TO_DO: "CREATE_TO_DO",
  REMOVE_TO_DO: "REMOVE_TO_DO",
  MARK_AS_COMPLETED: "MARK_AS_COMPLETED",
  GET_TODOS_API_REQUEST: "GET_TODOS_API_REQUEST",
  GET_TODOS_API_SUCCESS: "GET_TODOS_API_SUCCESS",
  GET_TODOS_API_FAILURE: "GET_TODOS_API_FAILURE",
  SET_UPDATE_TABS: "SET_UPDATE_TABS"
};
